---
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false

script:
  - cargo test
  - cargo doc --no-deps

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

env:
  global:
    secure: "ZKW24J4GBEf4HBsdMig0e0oML6mAxAc97rnVe7b5zpr16pFakVKT9XEBg4K3bk6RtSsiUZ1Hf/5eCPlfDproDjBHOALA27w9f9v1nMT4su2gKutThGJMixZ46tsywtXRh/blUAM6CHWMFHNhMolPXHbLyuLd8iUZvMJ9kE7NaoOA+kiBtxdYFgr4w/NrDekne8uFAcPZlWlmNe3BvafM+MNoOujg4tJc3ZGQnWNPK5X0I/+7Vzth5FM1ejEtb4YdxS83qNDFnU3PBGNGGr+JXC0lFwHmBJhAxHCBTmLfzcJyGZvEneWYGEvz8NiC8foTqxppqv87wI69nZvicatmAdBL89gyQUnG4PKk3yUlqtdlaBk4SszA36n7aqP6uBf+0TlSPeYsdxYOqCVt0pr6IwJDz9drNpB8gTBdI3JSbn64da3pMvVyprRMRMHd6Jigpt3TJig5mOqIwhF5OvA1nQXE7QmXrvnaZ71eql6khedOMMkjyqVVVEjE6F7sMwrqP4LaEkGQSGic7UoFdcUsLR3EvFb8eZKPzvGK4bpUF4qz1xr7MQno3u1A9zadWALq64Zeq5/gK4l1hTzNCkMZBS++TeoLsMvYvEdTfeI+YHdU1nBJ5q+gC4I99IBkU2BvyZ08n4mZfBSpTl5RXhnh0TcqA3o3mlwzyFy25j9CR+c="
